orbs:
  python: circleci/python@1.4.0

version: 2.1

workflows:
  main:
    jobs:
      - python/test:
          args: '.[dev,test]'
          pkg-manager: pip-dist
          pip-dependency-file: setup.py
          test-tool: pytest